server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ppab-service
          uri: lb:http://PPAB-SERVICE
          predicates:
            - Path=/api/v1/customers/**