server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ppab-service
          uri: lb:http://PPAB-SERVICE
          predicates:
            - Path=/ppab/**
            - Path=/associative/**
            - Path=/codeAA/**
            - Path=/codeBenef/**
            - Path=/codeCompo/**
            - Path=/codeG/**
            - Path=/codeOS/**
            - Path=/codeRt/**
            - Path=/codeType/**
            - Path=/compte/**
            - Path=/modeExecution/**
            - Path=/ptba/**
            - Path=/responsable/**
            - Path=/tauxChange/**
